### PR TITLE
Improve travis

### PR DESCRIPTION
**Pull request by kotoko**

### CODE REVIEW

**Comment by kotoko** [comment]
Tricks:
* https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
* https://docs.gradle.org/current/userguide/build_cache.html

**Comment by kotoko** [comment]
For some reason travis fails saving cache in backend build...

**Comment by kotoko** [comment]
I had to change `language:  java` to `language: generic`, because otherwise travis fails sending cache for backend task. It looks like it has a bug when sending file with name containing `[` or `]`. Luckily `language` is only small preset of settings.

**Comment by kotoko** [comment]
Empty cache:
https://travis-ci.org/codeloopeu/thehub/builds/570801249
Full cache:
https://travis-ci.org/codeloopeu/thehub/builds/570804765

**Comment by kotoko** [comment]
Seems working. Ready for review.

**Comment by pananimals** [comment]
LGTM

**Pull request merged**
